spring.datasource.url=${DB_URL:jdbc:postgresql://postgres:5432/walletdb}
spring.datasource.username=${DB_USERNAME:walletuser}
spring.datasource.password=${DB_PASSWORD:walletpass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

spring.jpa.open-in-view=false